### PR TITLE
OneDrive Client Updates

### PR DESCRIPTION
**Pull request by abraunegg**
Add additional runtime options:
- Add a --debug flag to debug https communication
- Add a local-first directive to sync from local source first
- Add capability to sync from a single local or remote folder
- Only sync if a sync option (sync|resync|monitor) is passed

I am also in the process of adding this client with these changes to the Cloud Replication Partners facility in the MyNAS Storage Appliance I develop (www.mynas.com.au) so that MyNAS will be able to sync to Microsoft OneDrive.

### CODE REVIEW

**Comment by RJaBi** [comment]
Just a heads up, I think that you might need to put
log.d
in the SOURCES section of the makefile (at the start?)

**Comment by thomasfedb** [comment]
You'd need to break this PR into multiple single-change PRs.

**Comment by thomasfedb** [comment]
This should probably be closed @skilion.

**Comment by abraunegg** [comment]
Obsoleted by #314

**Pull request closed without merging**
