### PR TITLE
Added SysV init script for compatibility with Ubuntu and derivates

### PR DESCRIPTION
**Pull request by hyronx**
The init script is based on https://github.com/fhd/init-script-template. I also added the check in Makefile if we have systemd running or not. Of course, you can edit this stuff how like.

Greetings

### CODE REVIEW

**Comment by Scimmia22** [comment]
I really don't think trying to detect systemd running is a good way to determine what to install. This can easily break in packaging.

There's also a reason very little software provides SysV init scripts. There's far too much variability between distros. What distros have you tested this on?

**Comment by hyronx** [comment]
But it is the common way to provide the same functionality like with systemd on systems running upstart and co. If you want to run this application automatically at boot on Ubuntu or standard Linux Mint you have to create such a script anyway...

**Comment by Scimmia22** [comment]
And autoconf would be a horrible way of doing it

**Comment by hyronx** [comment]
I haven't used autoconf anywhere.

**Comment by Scimmia22** [comment]
I was responding to the comment by CJxD

**Comment by hyronx** [comment]
My app messed up his comment. Sorry for that, too.

**Comment by skilion** [comment]
Thanks for your pull request but the most common init system is systemd right now. The adoption of SysV is fading and I would like to keep the project as lean and simple as possible.

**Pull request closed without merging**
