### PR TITLE
OneDrive Client Bugfixes & Enhancements

### PR DESCRIPTION
**Pull request by abraunegg**
* Fix 4xx errors including (412 pre-condition, 409 conflict)
* Fix Key not found: lastModifiedDateTime OneDrive API change
* Add Logging - log to a file (/var/log/onedrive/%username%.onedrive.log)
* Add http(s) debugging as a flag
* Add dont sync when just blindly running the application
* Add individual folder sync - ie ~/OneDrive/blah/ vs. syncing everything in ~/OneDrive/
* Add sync from local directory first rather than download first then upload
* Add upload long path check (400 & 430 character limitations for Business and Personal)
* Add upload only
* Add check for max upload file size before attempting upload
* Add systemd unit files for single & multi user configuration
* Add init.d file for older init.d based services
* Add Microsoft naming conventions and namespace validation for items that will be uploaded (#104)
* Add remaining free space counter at client initialisation
* Add upload file size validation & retry if does not match
* Resolve Issues #73, #121, #132, #224, #257, #294, #295, #297, #298, #300, #306, #315, #320, #329, #334, #337, #341 

**Outstanding Issues:**
* OneDrive generates a `nextLink value without skip or skiptoken` error when there are large changes. This is a bug with OneDrive and not this client - https://github.com/OneDrive/onedrive-api-docs/issues/844. This issue seems to only effect 'business' accounts.

### CODE REVIEW

**Comment by sbocquet** [comment]
Hi,

Nice improve of the project... Hoping this commit will come soon.
Do you think it could be possible to add an option to specify the log file, to have multiple log files in /var/log/onedrive ?

I'm actually using it on my NAS with multiple accounts to "synchronize" some dir with multiple OneDrive accounts (e.g. : Mine & My wife). It could be useful to have separate log file in that case.

Actually, I'm using a tweak with and /etc/init.d script to do it as I cannot create multiple services...

Have a nice day,

Cheers

**Comment by abraunegg** [comment]
It should be fairly easy to implement a flag for a custom logfile name. The other option is to grab the current username at runtime and add that to the logfile name.

Do you run the onedrive application as separate users today?

**Comment by sbocquet** [comment]
Thanks for your answer.

First to know, I'm on a DIY Debian NAS, so I manage the app the "Debian way".  Users conf dir are in /etc/OneDrive/username
At the moment, I'm starting the application as root. I'm searching for x user "dir" in /etc/OneDrive, and start OneDrive as a daemon for each user.

Here is the /etc/init.d/onedrive script.
[initd_onedrive.txt](https://github.com/skilion/onedrive/files/1854924/initd_onedrive.txt)

Some more infos:
```
root@home-server:~# systemctl status onedrive.service
● onedrive.service - LSB: OneDrive multi-client synchronization
   Loaded: loaded (/etc/init.d/onedrive; generated; vendor preset: enabled)
   Active: active (running) since Tue 2018-03-27 22:10:24 CEST; 11h ago
     Docs: man:systemd-sysv-generator(8)
  Process: 21245 ExecStart=/etc/init.d/onedrive start (code=exited, status=0/SUCCESS)
    Tasks: 2 (limit: 4915)
   CGroup: /system.slice/onedrive.service
           ├─21259 /usr/local/bin/onedrive --monitor --confdir=/etc/onedrive/St phane
           └─21266 /usr/local/bin/onedrive --monitor --confdir=/etc/onedrive/Virginie

mars 27 22:10:24 home-server systemd[1]: Starting LSB: OneDrive multi-client synchronization...
mars 27 22:10:24 home-server systemd[1]: Started LSB: OneDrive multi-client synchronization.
```

```
root@home-server:~# ls -al /var/run/onedrive/
total 8
drwxr-xr-x  2 root root   80 mars  27 22:10 .
drwxr-xr-x 29 root root 1160 mars  28 09:24 ..
-rw-r--r--  1 root root    6 mars  27 22:10 Stéphane.pid
-rw-r--r--  1 root root    6 mars  27 22:10 Virginie.pid
root@home-server:~# ls -al /var/log/onedrive/
total 16
drwxr-xr-x  2 root adm  4096 mars  26 20:27 .
drwxr-xr-x 15 root root 4096 mars  28 00:59 ..
-rw-r--r--  1 root adm  3484 mars  28 05:30 Stéphane.log
-rw-r--r--  1 root adm   316 mars  28 05:30 Virginie.log
```

**Comment by sbocquet** [comment]
I just compiled your sources to give a try.
There is one error in onedrive.d line 37 ('&error') ;)

Could be useful to have an option to specify the token too... as when I try to run OneDrive as a service, I have this error message :

onedrive.service

```
[Unit]
Description=OneDrive Free Client
Documentation=https://github.com/skilion/onedrive

[Service]
ExecStart=/usr/local/bin/onedrive -m --confdir="/etc/onedrive" --syncdir="/srv/dev-disk-by-label-DiskPool/"
Restart=always

[Install]
WantedBy=default.target
```

```
onedrive[18355]: Authorize this app visiting:
onedrive[18355]: https://login.microsoftonline.com/common/oauth2/v2.0/authorize?client_id=22c49a0d-d21c-4792-aed1-8f163c982546&scope=files.readwrite%20files.readwrite.all%20offline_access&response_type=code&redirect_uri=https://login.microsoftonline.com/common/oauth2/nativeclient
onedrive[18355]: Enter the response uri: Invalid uri
onedrive[18355]: Could not initialize the OneDrive API
systemd[1268]: onedrive.service: Main process exited, code=exited, status=1/FAILURE
systemd[1268]: onedrive.service: Failed with result 'exit-code'.
```

It seems that the token is not found as it asks to create a new one...

**Comment by abraunegg** [comment]
Interesting re the error - as without the '&' using the DMD reference compiler (dmd-2.078.3 from https://dlang.org/download.html) the original code fails to compile.

What d compiler are you using?

**Comment by sbocquet** [comment]
root@omvglbvprd1:~# dmd --version
DMD64 D Compiler v2.079.0
Copyright (C) 1999-2018 by The D Language Foundation, All Rights Reserved written by Walter Bright

root@omvglbvprd1:~# uname -a
Linux omvglbvprd1 4.14.0-0.bpo.3-amd64 #1 SMP Debian 4.14.13-1~bpo9+1 (2018-01-14) x86_64 GNU/Linux

**Comment by sbocquet** [comment]
I installed it like this:

```
wget http://master.dl.sourceforge.net/project/d-apt/files/d-apt.list -O /etc/apt/sources.list.d/d-apt.list
apt-get update && sudo apt-get -y --allow-unauthenticated install --reinstall d-apt-keyring
apt-get update && sudo apt-get install dmd-compiler dub
```

**Comment by abraunegg** [comment]
I guess dmd is installing OK for you - I build everything under CentOS using mock using the following:

```
DFLAGS = -g -ofonedrive -O -L-lcurl -L-lsqlite3 -L-ldl -J. -I/usr/include/dmd/phobos/ -I/usr/include/dmd/druntime/import -L--export-dynamic
```

What is your build command?

In the build log output I have this:

```
Executing(%build): /bin/sh -e /var/tmp/rpm-tmp.x2cNds
+ umask 022
+ cd /builddir/build/BUILD
+ cd onedrive-1.3
+ LANG=C
+ export LANG
+ unset DISPLAY
+ cd /builddir/build/BUILD/onedrive-1.3/
+ make
dmd -g -ofonedrive -O -L-lcurl -L-lsqlite3 -L-ldl -J. -I/usr/include/dmd/phobos/ -I/usr/include/dmd/druntime/import -L--export-dynamic src/config.d src/itemdb.d src/log.d src/main.d src/moni
tor.d src/onedrive.d src/qxor.d src/selective.d src/sqlite.d src/sync.d src/upload.d src/util.d
sed "s|@PREFIX@|/usr|g" onedrive.service.in > onedrive.service
+ exit 0
```

**Comment by sbocquet** [comment]
I haven't build the compiler as it is already packaged for Debian.

```
root@omvglbvprd1:/sharedfolders/Developpement/onedrive# make
dmd -g -ofonedrive -O -L-lcurl -L-lsqlite3 -L-ldl -J. src/config.d src/itemdb.d src/log.d src/main.d src/monitor.d src/onedrive.d src/qxor.d src/selective.d src/sqlite.d src/sync.d src/upload.d src/util.d
```

**Comment by abraunegg** [comment]
OK - so your make line differs from mine - with the -I for additional includes and -L--export-dynamic

When I revert the line 37 change, when I compile I get this:

```
dmd -g -ofonedrive -O -L-lcurl -L-lsqlite3 -L-ldl -J. -I/usr/include/dmd/phobos/ -I/usr/include/dmd/druntime/import -L--export-dynamic src/config.d src/itemdb.d src/log.d src/main.d src/monitor.d src/onedrive.d src/qxor.d src/selective.d src/sqlite.d src/sync.d src/upload.d src/util.d
src/onedrive.d(37): Error: function std.json.toJSON (const(JSONValue*) root, const(bool) pretty = false, const(JSONOptions) options = cast(JSONOptions)0) is not callable using argument types (const(JSONValue), bool)
make: *** [onedrive] Error 1
```

**Comment by sbocquet** [comment]
If I let your code, I have this:

```
src/onedrive.d(37): Error: function std.json.toJSON(ref const(JSONValue) root, const(bool) pretty = false, const(JSONOptions) options = cast(JSONOptions)0) is not callable using argument types (const(JSONValue)*, bool)
src/onedrive.d(37):        cannot pass rvalue argument &error of type const(JSONValue)* to parameter ref const(JSONValue) root
Makefile:29: recipe for target 'onedrive' failed
make: *** [onedrive] Error 1
```

**Comment by abraunegg** [comment]
Very weird ... 

What is the contents of your dmd.conf file?

**Comment by sbocquet** [comment]
```
# cat /etc/dmd.conf
;
; dmd.conf file for dmd
;
; dmd will look for dmd.conf in the following sequence of directories:
;   - current working directory
;   - directory specified by the HOME environment variable
;   - directory dmd resides in
;   - /etc directory
;
; Names enclosed by %% are searched for in the existing environment and inserted
;
; The special name %@P% is replaced with the path to this file
;

[Environment32]
DFLAGS=-I/usr/include/dmd/phobos -I/usr/include/dmd/druntime/import -L-L/usr/lib/i386-linux-gnu -L--export-dynamic

[Environment64]
DFLAGS=-I/usr/include/dmd/phobos -I/usr/include/dmd/druntime/import -L-L/usr/lib/x86_64-linux-gnu -L--export-dynamic -fPIC
```

**Comment by abraunegg** [comment]
Hrmm .. matches what I have here .. I wonder what is going on ... 

Will upgrade the dmd  version to match yours - as mine is 1 version behind - unsure what else to look at presently .. will have to look at this tomorrow further

**Comment by sbocquet** [comment]
Yes, for me, it seems the same options... very Strange.

Just tell me if you want me to test something. I used to be a C dev a long time ago but I can still test ;)

**Comment by abraunegg** [comment]
I updated my DMD version to 2.079.0 and successfully built my code & patch without the '&' on line 37 ...

Will update my branch etc to take the '&' out and update the notes that you need to use the '2.079.0' of the reference compiler.

**Comment by sbocquet** [comment]
OK.
Thought about the log and token options. Could be nice to have the same thing as syncdir, to put it in the config file or erase by the command line.
What do you think of that ?
Cheers,

**Comment by sbocquet** [comment]
Thanks Alex to all those upgrades. Works like a charm with multi-users now ;)

**Comment by Uniqen** [comment]
Thanks for the upgrades in this pull request!

I'm using this to upload logs and backups of a small application and was excited to try out the upload-only feature. Apparently the upload-only also remove files from onedrive when they are removed from the local folder. In my case it would be interesting to keep the backups on onedrive but to be able to remove them from the server. Any possibility to add an additional flag for this?

I was running (in docker container) the following command.
`onedrive --synchronize --upload-only  --monitor --confdir /config --syncdir /onedrive`

**Comment by pdelbeato** [comment]
Great work! Thank you guy!
At the moment, I'm facing an issue.
During a resync, a large file was uploading. Something goes wrong, and the program stopped working. I restarted, without -resync option. And then: "Trying to restore the upload session ... The upload session is expired" and the program exits.

Here the verbose (my version is the last: onedrive v1.1.1-41-gd3f4064):
```
$ onedrive --verbose --upload-only --confdir="~/.config/onedriveTera"
Loading config ...
Using Config Dir: /home/masterhtpc/.config/onedriveTera
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: /bigtank/
Initializing the Synchronization Engine ...
Account Type: business
Default Drive ID: ****
Default Root ID: ****
Remaining Free Space: 5413916094905
Trying to restore the upload session ...
The upload session is expired
```

Any ideas? Thanks!

**Comment by abraunegg** [comment]
Yes - your missing the `--synchronize` flag - it should only sync if you use that flag.

This is a change in operation when using the #314 branch

**Comment by speedster-pta** [comment]
Thanks to everyone who's been working to make this work. I've installed and managed to get most of the application working, but have recently run into the lastModifiedDateTime error. I read on the forum that I should upgrade to #314. However, when I run git clone https://github.com/abraunegg/onedrive.git I get the following error: "fatal: destination path 'onedrive' already exists and is not an empty directory."

Should I rm that directory and try again? I'm asking as I don't want to rm something that would be needed to keep running onedrive.

**Comment by sbocquet** [comment]
Yes, you have too delete the dir before.

**Comment by abraunegg** [comment]
> thx for this pull, hope it becomes active, if author have left the ship, maybe it could be forked instead.
Either way, using it and seems to be working very good.

Thanks. I think you can safely switch to my fork already:
```
git clone https://github.com/abraunegg/onedrive.git
```

**Comment by sbocquet** [comment]
Yes, we can ;) !

**Comment by andystevens91** [comment]
Hi, I started using this fork (after uninstalling the skilion release) and I noticed some errors.

1. > apr 27 01:38:32 andrea-N240JU onedrive[4462]: /usr/local/bin/onedrive: error while loading shared libraries: libphobos2-ldc.so.74: cannot open shared object file: No such file or directory
2. > apr 27 01:40:29 andrea-N240JU onedrive[4600]: /usr/local/bin/onedrive: error while loading shared libraries: libdruntime-ldc.so.74: cannot open shared object file: No such file or directory
3. > apr 27 01:44:56 andrea-N240JU onedrive[4767]: /usr/local/bin/onedrive: symbol lookup error: /usr/local/bin/onedrive: undefined symbol: _D6object6Object5opCmpMFC6ObjectZi

I managed to solve the first 2 by soft-linking the libraries I have on my system:
`sudo ln -s /usr/lib/x86_64-linux-gnu/libphobos2-ldc-shared.so.78 /usr/lib/x86_64-linux-gnu/libphobos2-ldc.so.74
`
`sudo ln -s /usr/lib/x86_64-linux-gnu/libdruntime-ldc-shared.so.78 /usr/lib/x86_64-linux-gnu/libdruntime-ldc.so.74
`

For the third issue I have no idea .
I'm running your fork of the client on Ubuntu 18.04 (just updated).

**Comment by abraunegg** [comment]
How are you building the client?

What version of dmd are you using?

**Comment by abraunegg** [comment]
Making that sysctl change makes sense if your using monitor mode which uses inotify.

A value of 32768 is potentially too low for a large local repository, so really need to provide advice on how best to set that & set in a permanent fashion.

**Comment by andystevens91** [comment]
Hi, I just want to let you know that error 412 (Precondition failed) still happens.

**Comment by andystevens91** [comment]
I'll try to reproduce the crash, but it happens quite randomly. By the way, last time it happened the client crashed, automatically restarted, and continued uploading like nothing happened.
Is there any way to run the client as a daemon with the `--verbose` option?

**Comment by abraunegg** [comment]
It depends on how your running it as a daemon:

init.d - the sh script that runs the application already specifies the `--verbose` option

systemd - edit the `ExecStart=` to include the `--verbose` option

The log file for the application should be (by default) in /var/log/onedrive/ under the username that runs the service. If the application cannot write to that location, the log file will be in ~/

**Comment by andystevens91** [comment]
Hi. Sorry but I was out of town these two days and I had no way of trying to collect that log. I uploaded it on pastebin at [this link](https://pastebin.com/4c97SD1k). After the last line of the log the client resumes its work "from scratch", checking all folders for changes.

The file that triggered the error should be either this one, Albert_Costa_0002.jpg:
albert_costa_0002
or this one, Albert_Costa_0006.jpg:
albert_costa_0006

(There are 6 files in that local folder, and I can see only 4 in the onedrive web interface, so the client failed while uploading one of these 2, as you can see here: on the left there is the web interface, on the right the local folder. The missing files are Albert_Costa_0002.jpg and Albert_Costa_0006.jpg)
screenshot from 2018-05-01 23-54-38

**Comment by abraunegg** [comment]
@andystevens91 

I can reproduce the issue 100% of the time again and I have totally re-worked the fix for the 412 issue.

Commit 0b5dc66507fd1b78fd06df4f99f6134cedbbb903 should resolve the issue as with my test data, I get the error, I get the logging saying that the error was received & handled gracefully. When I check OneDrive the file that returned the issue on is there and accessible.

**Comment by andystevens91** [comment]
Everything seems fine to me now. Great job!

**Comment by mcmtroffaes** [comment]
I'm in a situation where I cannot write to /var/log, and despite the fallback to write to the home folder (I checked the code), I'm still getting an error:

```
$ ./onedrive
std.file.FileException@std/file.d(2954): /var/log/onedrive/: Permission denied
----------------
/home/stats/dma0mt/dlang/dmd-2.080.0/linux/bin64/../../src/phobos/std/file.d:238 @safe bool std.file.cenforce!(bool).cenforce(bool, lazy const(char)[], immutable(char)[], ulong) [0x58795f]
??:? @safe bool std.file.ensureDirExists!().ensureDirExists(const(char[])) [0x5d8081]
??:? @safe void std.file.mkdirRecurse(const(char[])) [0x5d6a04]
src/main.d:106 _Dmain [0x592e3a]
```

The offending line seems to be https://github.com/abraunegg/onedrive/blob/0b1ca6dbfd5e1d8d5dc468522512dbc52bfabc5a/src/main.d#L106 so I think it's just a matter of detecting this situation where the user cannot write to /var/log also there. Commenting out the line fixed the problem.

Let me know if it is better to open a separate issue on your repository for this, @abraunegg

**Comment by abraunegg** [comment]
@mcmtroffaes 
Thanks for finding that issue - it looks like that check is better off served in the log.d rather than in main as it is failing if it cannot create it ..

**Comment by mcmtroffaes** [comment]
Yes, completely agreed!

**Comment by abraunegg** [comment]
yep - saw that as well - the XDG stuff tho is only available on systems where X11 is present - thanks fro fixing up the logic there

On the log dir piece - the makefile also specifies to `mkdir -p /var/log/onedrive` as well .. so did that fail? how did you run `make` initially?

**Comment by mcmtroffaes** [comment]
Oh, yeah, that's a totally good question. I just ran make without make install, since I don't have admin rights on the machine.

**Comment by mcmtroffaes** [comment]
Thanks for the quick fix! I can confirm this is completely working on a system with no /var/log/ access.

**Comment by mcintyrechris** [comment]
@abraunegg you need to just start publishing your fork as the new fork to download & install (I do this already) as this repo seems dead.

**Comment by mcintyrechris** [comment]
@abraunegg I've just started to clone/build from your fork of this application now, thanks for the hard work and support!

**Comment by speedster-pta** [comment]
thanks for the great work you guys are doing on this. What is the best way to update to the latest build?

**Comment by abraunegg** [comment]
@speedster-pta 
The easiest way to get the latest code is:
```
git clone https://github.com/abraunegg/onedrive.git
cd onedrive
make
sudo make install
```

**Comment by ShadySquirrel** [comment]
Makefile install should support DESTDIR variable, which is necessary for package creation. It's mostly fine, except lines 25 to 27 which should be changed to:
```
mkdir -p $(DESTDIR)/var/log/onedrive
chown root.users $(DESTDIR)/var/log/onedrive
chmod 0775 $(DESTDIR)/var/log/onedrive
```
and also line 29 should be changed to:
```
install -D -m 644 logrotate/onedrive.logrotate $(DESTDIR)/etc/logrotate.d/onedrive
```
Also, there are possibly some needed changes under `uninstall` section, to support uninstalling for different destination directory, but I haven't tested them because my goal was to create an Arch Linux package.

Without mentioned changes, distribution package creation fails, because Makefile is simply ignoring the fact that we're not installing to system root, and that installation is done by regular user, so some permissions may be missing.. Error found and solution tested with PKGBUILD adapted from original one found on AUR (package name is `onedrive-git`, my PKGBUILD is unpublished but I can make a gist if someone is interested).

I think that's a proper solution [according to GNU coding standards](https://www.gnu.org/prep/standards/html_node/DESTDIR.html), but you may have a better idea, so I didn't want to create unecessary pull requests.

**Comment by abraunegg** [comment]
@ShadySquirrel 
Feel free to submit a PR against my codebase as this one appears abandoned by the original author

**Comment by ShadySquirrel** [comment]
Okay. I'll open a PR later today.

**Comment by saschpe** [comment]
Seems to work for me though it's likely better to split into a bunch of smaller / individual PRs

**Comment by abraunegg** [comment]
@saschpe 
Thanks - however given this PR has been open for 2 months with active development & replaced #82 which was open for 12 months with development and no response from the original author - each individual commit can be separately reviewed. 

The original codebase appears to have been abandoned.

**Comment by abraunegg** [comment]
Closing this PR to 'skilion' branch.

For anyone in the future, if you wish to use the latest version of the client, clone from here:
```
git clone https://github.com/abraunegg/onedrive.git
```

**Pull request closed without merging**
