### PR TITLE
Update config

### PR DESCRIPTION
**Pull request by SgLy**
to prevent crash caused by missing skip_dir parameter

### CODE REVIEW

**Comment by Scimmia22** [comment]
This also needs to be done in the defaults in config.d

**Comment by SgLy** [comment]
@Scimmia22 you are right...as well as several lines of code in other files. I'll try to manage this

**Comment by Scimmia22** [comment]
hmm, might want to set them to the previous default as well
skip_dir = ".*"

Of course, all of this depends on skilion pulling it, which appears to be a long shot

**Comment by skilion** [comment]
This workaround is not needed anymore. Fixed in 88d2a940782813253ea6a0581267d836a8f90a4e

**Pull request closed without merging**
