### PR TITLE
:warning: REPO IS UN-MAINTAINED AND CAUSING DATA CORRUPTION :warning:

### PR DESCRIPTION
**Pull request by jakebrinkmann**
~~Hi, today I was on an Arch system and immediately began having the same problem as https://github.com/skilion/onedrive/issues/430~~

~~This PR is a re-Implementation of https://github.com/skilion/onedrive/pull/431/ (thx @Popa21). Feel free to close my issue in favor of that one, to give proper credit. I only open this PR for your convenience.~~

~~I have tested that it is working without surprises. I built the executable inside an Arch docker container. Here are my [Gist notes](https://gist.github.com/jakebrinkmann/878f06014642556cd7836a04be145027)  on that for reference~~

~~Thanks a lot for your hard work on this, it is simple and does exactly what I need!~~

---

Yikes, this application just corrupted several gigabytes of my files. Beware :disappointed:

### CODE REVIEW

**Comment by Popa21** [comment]
Patch is already implemented in forked repository https://github.com/abraunegg/onedrive. It seems that this repository doesn't get any updates anymore.

**Comment by jakebrinkmann** [comment]
@Popa21 thanks again, yes, interestingly I found the skilion/onedrive version works better for me so re-opened for consideration

**Comment by abraunegg** [comment]
@jakebrinkmann 
It would be interesting to understand what you mean by that the skilion version works better as many many bugs have been fixed in my fork

**Comment by Popa21** [comment]
See https://github.com/abraunegg/onedrive/issues/251#issuecomment-442514561. There's also the option of an docker image with only minimal features.

**Comment by abraunegg** [comment]
@jakebrinkmann

Which version corripted your data - this original version or my fork?

**Comment by abraunegg** [comment]
@jakebrinkmann 
I would ensure that you open a case on this repo with any findings you have & that you are having data loss. 

If you find anything, please also a case on my repo so this can be validated and checked

**Pull request closed without merging**
