### PR TITLE
make install work to make it possible creating packages

### PR DESCRIPTION
**Pull request by a4z**
add DESTDIR, PREFIX, LIBSUFFIX
example:
make install DESTDIR=/tmp/pkgs/onedrive PREFIX=/usr
and than put the content of DESTDIR into an rpm, dep, or other Linux
package

### CODE REVIEW

**Comment by Scimmia22** [comment]
Good luck I've had #46 sitting here since April, doing almost exactly the same thing.

**Comment by thomasfedb** [comment]
Would be great if this could be combined with #46.

**Comment by a4z** [comment]
#46 solves 2 problems in one commit which are not necessarily connected.
so actually it would be more smart to not also combine this commit, but take the part of #46, handle additional config files, and make an extra commit/pull request out of it.  
feel free to do this, @thomasfedb , for me, as long as the author @skilion is not interested in fixing/merging issues or at least giving feedback for people that want to help, there is no interest in doing so. but maybe @Scimmia22 want's to give this a new trial?

**Comment by Scimmia22** [comment]
@a4z, it's not in the same commit, just in the same pull request. I did it that way because it kind of depends on the previous commits. Without the ability to sanely change PREFIX, it makes no sense.

**Comment by skilion** [comment]
Fixed in 83a958df598a8457cb618d659a7104608aaf14a0

**Pull request closed without merging**
